### ISSUE TITLE
Error on publishing page

### ISSUE THREAD

**Issue by fujihara** [PiranhaCMS/Piranha#370]
This error happen when I try to publish any page. 

The trace says database connection problem but I can create, save the drafts and use all other operations that require database access. Only at publish time I get this error.

System.Data.SqlClient.SqlException (0x80131904): Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---&gt; System.ComponentModel.Win32Exception (0x80004005): The wait operation timed out
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean&amp; dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task&amp; task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task&amp; task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteScalar()
   at Piranha.Data.ActiveRecord`1.GetScalar(String statement, Object[] args) in c:\Proj\GitHub\Piranha-2.2\Piranha\Data\ActiveRecord.cs:line 397
   at Piranha.Models.Manager.PageModels.EditModel.&lt;&gt;c__DisplayClassa.&lt;SaveAll&gt;b__4(Region r) in c:\Proj\GitHub\Piranha-2.2\Piranha\Models\Manager\PageModels\EditModel.cs:line 396
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Piranha.Models.Manager.PageModels.EditModel.SaveAll(Boolean draft) in c:\Proj\GitHub\Piranha-2.2\Piranha\Models\Manager\PageModels\EditModel.cs:line 457
   at Piranha.Areas.Manager.Controllers.PageController.Edit(Boolean draft, EditModel pm) in c:\Proj\GitHub\Piranha-2.2\Piranha\Areas\Manager\Controllers\PageController.cs:line 137
ClientConnectionId:8513f3a2-3da4-4aca-9a22-00309356cd71

**Comment by tidyui** [comment]
Hi there! What database are you using and how does your connection string look like. Piranha CMS requires MARS to be enabled, and since you're getting a timeout I'm guessing a database-operation within the transaction is being blocked by another.

Regards

Håkan

**Comment by tidyui** [comment]
Did you get this sorted out? Can I close the issue?
