### ISSUE TITLE
Publish error after database migration

### ISSUE THREAD

**Issue by dpfisher** [PiranhaCMS/Piranha#444]
Hello, 

I am having issues with publishing once I have migrated the database from the development to live server

I believe it is very similar to unresolved issue #370

I receive this error:
System.Data.SqlClient.SqlException (0x80131904): Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---&gt; System.ComponentModel.Win32Exception (0x80004005): The wait operation timed out
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean&amp; dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task&amp; task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task&amp; task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteScalar()
   at Piranha.Data.ActiveRecord`1.GetScalar(String statement, Object[] args)
   at Piranha.Models.Manager.PostModels.EditModel.&lt;&gt;c__DisplayClass13.&lt;SaveAll&gt;b__8(Property p)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Piranha.Models.Manager.PostModels.EditModel.SaveAll(Boolean draft)
   at Piranha.Areas.Manager.Controllers.PostController.Edit(Boolean draft, EditModel m)
ClientConnectionId:451433b5-1386-4a0f-aeeb-00fc5144dd2e
Error Number:-2,State:0,Class:11 

I used the basic export tool in sql server management studio to migrate the database from UAT to live. The website displays all content correctly and I can see post and page data, but just cant update it.

My connection string is as follows implementing mars

  <add name="piranha" connectionString="data source=MyServer;Initial Catalog=CMS;Integrated Security=True;MultipleActiveResultSets=true" providerName="System.Data.SqlClient" />

I experienced this problem when moving from local to UAT and was hoping that as my UAT server is similar to the live server this issue would not recur when moving to live.

I use VS2013 and used nuget to download Piranha MVC 2.2.5

I've used piranha on multiple sites before and am always an advocate for it so hopefully I wont end up with egg on my face with this one and the design team.

**Comment by tidyui** [comment]
Well it's highly unlikely that there's anything wrong with your application since it's working fine in your development environment and you've done several projects before. I never got any answers in the issue you referenced, so maybe we can sort this out now.

Obviously there's something with the database in the production environment that makes the it time out. Can you get some more information about the Database (version, settings) in the production environment?

**Comment by dpfisher** [comment]
My concern was that it was an environmental issue so I have just performed a test where I created a new database on the same server with the default settings (that were used on the original)

I used the export wizard to copy the database tables over, the exact same issue happened again and I think this is where I went wrong.

For anyone else running into this issue, none of the primary key information got copied over so I had  tables without primary keys, so no surprise we were getting timeout issues.

I very much appreciate how quickly you responded to my query, yet another reason why everyone should be using Piranha Cms

Happy Friday
